spring.application.name=api

spring.datasource.url=jdbc:postgresql://localhost:5432/api-auth
spring.datasource.username=auth
spring.datasource.password=dominouno11

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=b2aaaaa3b6c7fa7ea813dc3295b6f158dc2a13d0d067c9ac0fb21fa1213fba1f
jwt.expiration=3600